"""initial migration

Revision ID: 004b53756417
Revises: 71f9651db5d6
Create Date: 2017-04-21 22:44:54.798195

"""

# revision identifiers, used by Alembic.
revision = '004b53756417'
down_revision = '71f9651db5d6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('rolename', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['rolename'])
    op.drop_column('roles', 'name')
    op.add_column('users', sa.Column('e_mail', sa.String(length=64), nullable=True))
    op.drop_index('email', table_name='users')
    op.create_unique_constraint(None, 'users', ['e_mail'])
    op.drop_column('users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'e_mail')
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('name', 'roles', ['name'], unique=True)
    op.drop_column('roles', 'rolename')
    ### end Alembic commands ###
