"""follow_foreignkey

Revision ID: 023aba24c214
Revises: 7b4839ed7948
Create Date: 2017-04-23 13:54:13.503159

"""

# revision identifiers, used by Alembic.
revision = '023aba24c214'
down_revision = '7b4839ed7948'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    ### end Alembic commands ###
