"""randomwords

Revision ID: 18a5bcaa7c3b
Revises: 7749e0ea81c9
Create Date: 2017-04-27 01:24:24.016366

"""

# revision identifiers, used by Alembic.
revision = '18a5bcaa7c3b'
down_revision = '7749e0ea81c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('randomwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('str', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('randomwords')
    ### end Alembic commands ###
