"""'body_html'

Revision ID: 2f8bc0d28a12
Revises: c91f7f826b5a
Create Date: 2017-04-23 01:40:06.159784

"""

# revision identifiers, used by Alembic.
revision = '2f8bc0d28a12'
down_revision = 'c91f7f826b5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
