"""'Role.rolename'

Revision ID: 71f9651db5d6
Revises: 6945e05b474f
Create Date: 2017-04-21 22:39:16.964664

"""

# revision identifiers, used by Alembic.
revision = '71f9651db5d6'
down_revision = '6945e05b474f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('rolename', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'rolename')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('rolename', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('rolename', 'roles', ['rolename'], unique=True)
    op.drop_column('roles', 'name')
    ### end Alembic commands ###
