"""follow

Revision ID: 7b4839ed7948
Revises: 2f8bc0d28a12
Create Date: 2017-04-23 13:46:04.491066

"""

# revision identifiers, used by Alembic.
revision = '7b4839ed7948'
down_revision = '2f8bc0d28a12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    ### end Alembic commands ###
