"""empty message

Revision ID: beae3db9d62b
Revises: 18a5bcaa7c3b
Create Date: 2017-07-22 21:20:40.975309

"""

# revision identifiers, used by Alembic.
revision = 'beae3db9d62b'
down_revision = '18a5bcaa7c3b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmpwords', sa.Column('str', sa.String(length=64), nullable=True))
    op.drop_column('tmpwords', 'word')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmpwords', sa.Column('word', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('tmpwords', 'str')
    ### end Alembic commands ###
