"""permission

Revision ID: c91f7f826b5a
Revises: cf597426d079
Create Date: 2017-04-22 14:55:43.364373

"""

# revision identifiers, used by Alembic.
revision = 'c91f7f826b5a'
down_revision = 'cf597426d079'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('Permissions', sa.Integer(), nullable=True))
    op.drop_column('roles', 'pemissions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('pemissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('roles', 'Permissions')
    ### end Alembic commands ###
